### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by k911** [miquido/alertmanager-webhook-forwarder#3]
### Documentation

- [ ] Example usage
- [ ] Writing message templates in formats

  * `Gotemplate-Text`
  * `Gotemplate-YAML`
  * `Jsonnet`

### Deployment

- [ ] Use [goreleaser](https://github.com/goreleaser/goreleaser) for creating releases
- [x] Use `/docs` strategy for deploying GitHub Pages (https://github.com/miquido/alertmanager-webhook-forwarder/commit/feb6a11f53fbd9140a30fddae6b2e073c5c51fe4)
- [x] Kustomization for Kubernetes deployment: [docs/examples/kubernetes](https://github.com/miquido/alertmanager-webhook-forwarder/tree/develop/docs/examples/kubernetes) (#13)
- [x] HTTP Server graceful shutdown (#13)

### GitHub

- [ ] Description
- [ ] Contributing guidelines 
- [ ] Code of conduct
- [ ] Pull request templates
- [ ] Issue templates

### Features

- [ ] AWS Lambda executable
- [ ] Dynamic Templates (Choose dynamically proper template based on simple conditions, like [elastic beats](https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#defining-processors) do) 
- [ ] Hangouts Chat templates for Bitbucket webhooks

### CI

- [ ] Configure Test Suite

  * Unit tests
  * Functional/feature tests
